import type {
  PlatformOverview,
  ToolCategory,
  ToolItem,
  ToolPlatform,
} from "./types";

export const CATEGORY_TABS: ToolCategory[] = [
  "全部",
  "系统",
  "开发",
  "运维",
  "网络",
  "效率",
];

export const PLATFORM_TABS: Array<"全部" | ToolPlatform> = [
  "全部",
  "Windows",
  "Linux",
  "macOS",
  "Web",
];

export const PLATFORM_OVERVIEWS: PlatformOverview[] = [
  {
    platform: "Windows",
    title: "Windows 工具",
    description: "本地检索、远程管理、开发环境与终端整合为主。",
  },
  {
    platform: "Linux",
    title: "Linux 工具",
    description: "偏向服务器维护、终端会话、代理与部署相关能力。",
  },
  {
    platform: "macOS",
    title: "macOS 工具",
    description: "兼顾开发终端、效率工具与跨平台工作流。",
  },
  {
    platform: "Web",
    title: "Web 工具",
    description: "以在线图表、配置面板、轻量管理工具为主。",
  },
];

export const CURATED_TOOLS: ToolItem[] = [
  {
    id: "powershell-7",
    name: "PowerShell 7",
    summary: "跨平台命令行与自动化脚本工具，适合系统管理与批处理。",
    category: "系统",
    platforms: ["Windows", "Linux", "macOS"],
    tags: ["Shell", "脚本", "自动化"],
    note: "适合统一多平台脚本环境。",
    detailUrl: "https://github.com/PowerShell/PowerShell",
    downloadUrl: "https://github.com/PowerShell/PowerShell/releases/latest",
  },
  {
    id: "everything",
    name: "Everything",
    summary: "Windows 本地文件秒级检索，适合快速定位软件包与文档。",
    category: "效率",
    platforms: ["Windows"],
    tags: ["搜索", "文件", "索引"],
    note: "本地资源管理效率很高。",
    detailUrl: "https://www.voidtools.com/",
    downloadUrl: "https://www.voidtools.com/downloads/",
  },
  {
    id: "wsl",
    name: "WSL",
    summary: "在 Windows 内直接使用 Linux 工具链，方便开发与运维联调。",
    category: "开发",
    platforms: ["Windows"],
    tags: ["Linux", "开发环境", "终端"],
    note: "适合本地复现服务器环境。",
    detailUrl: "https://learn.microsoft.com/windows/wsl/",
    downloadUrl: "https://aka.ms/wslstorepage",
  },
  {
    id: "tmux",
    name: "tmux",
    summary: "终端会话复用工具，适合远程会话保活与多任务操作。",
    category: "运维",
    platforms: ["Linux", "macOS"],
    tags: ["终端", "会话", "SSH"],
    note: "服务器常驻任务很好用。",
    detailUrl: "https://github.com/tmux/tmux",
    downloadUrl: "https://github.com/tmux/tmux/releases/latest",
  },
  {
    id: "docker",
    name: "Docker",
    summary: "容器化打包与运行工具，适合隔离服务与统一部署环境。",
    category: "运维",
    platforms: ["Windows", "Linux", "macOS"],
    tags: ["容器", "部署", "镜像"],
    note: "适合服务封装与环境一致性。",
    detailUrl: "https://www.docker.com/",
    downloadUrl: "https://www.docker.com/products/docker-desktop/",
  },
  {
    id: "wireshark",
    name: "Wireshark",
    summary: "网络抓包分析工具，用于排查协议、延迟与异常请求。",
    category: "网络",
    platforms: ["Windows", "Linux", "macOS"],
    tags: ["抓包", "协议", "排障"],
    note: "定位网络问题很直接。",
    detailUrl: "https://www.wireshark.org/",
    downloadUrl: "https://www.wireshark.org/download.html",
  },
  {
    id: "moba",
    name: "MobaXterm",
    summary: "Windows 下集成 SSH、SFTP、X11 的远程终端工具。",
    category: "运维",
    platforms: ["Windows"],
    tags: ["SSH", "SFTP", "远程"],
    note: "适合一体化远程管理。",
    detailUrl: "https://mobaxterm.mobatek.net/",
    downloadUrl: "https://mobaxterm.mobatek.net/download.html",
  },
  {
    id: "tabby",
    name: "Tabby",
    summary: "现代化终端工具，支持多标签、多配置和跨平台同步。",
    category: "系统",
    platforms: ["Windows", "Linux", "macOS"],
    tags: ["终端", "跨平台", "连接管理"],
    note: "本地和服务器切换更顺手。",
    detailUrl: "https://tabby.sh/",
    downloadUrl: "https://github.com/Eugeny/tabby/releases/latest",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    summary: "Markdown 笔记工具，适合整理知识、脚本与运维文档。",
    category: "效率",
    platforms: ["Windows", "Linux", "macOS"],
    tags: ["笔记", "Markdown", "知识库"],
    note: "适合长期沉淀工具文档。",
    detailUrl: "https://obsidian.md/",
    downloadUrl: "https://obsidian.md/download",
  },
  {
    id: "drawio",
    name: "draw.io",
    summary: "在线流程图工具，适合画系统架构、部署链路与接口关系。",
    category: "效率",
    platforms: ["Web"],
    tags: ["图表", "流程图", "设计"],
    note: "画部署结构很省事。",
    detailUrl: "https://www.diagrams.net/",
    downloadUrl: "https://app.diagrams.net/",
  },
  {
    id: "vscode",
    name: "VS Code",
    summary: "轻量级代码编辑器，支持插件扩展、远程开发与终端整合。",
    category: "开发",
    platforms: ["Windows", "Linux", "macOS"],
    tags: ["编辑器", "插件", "远程开发"],
    note: "适合脚本、前后端与配置文件统一维护。",
    detailUrl: "https://code.visualstudio.com/",
    downloadUrl: "https://code.visualstudio.com/Download",
  },
  {
    id: "nginx-ui",
    name: "Nginx UI",
    summary: "Web 化管理 Nginx 配置与证书，适合站点维护与代理调整。",
    category: "网络",
    platforms: ["Linux", "Web"],
    tags: ["Nginx", "证书", "代理"],
    note: "适合轻量化站点管理。",
    detailUrl: "https://github.com/0xJacky/nginx-ui",
    downloadUrl: "https://github.com/0xJacky/nginx-ui/releases/latest",
  },
];
